#!/usr/bin/env python3
"""Connect front-side SMD ground pads directly to the continuous L2 plane.

These are 0.20/0.10 mm filled and capped microvias-in-pad.  They are used only
on GND pads and avoid free-standing stitching vias near fine-pitch signals.
"""
import os
import pcbnew

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PATH = os.environ.get(
    "FC_BOARD_PATH", os.path.join(ROOT, "ESP32_FlightController.kicad_pcb")
)
board = pcbnew.LoadBoard(PATH)
gnd = board.FindNet("GND")
if not gnd:
    raise RuntimeError("GND net not found")

# Remove only vias previously generated by this script (identified by their
# exact microvia geometry and GND net) so reruns are deterministic.
for item in list(board.GetTracks()):
    if (isinstance(item, pcbnew.PCB_VIA) and item.GetNetname() == "GND"
            and item.GetViaType() == pcbnew.VIATYPE_MICROVIA
            and item.GetWidth() in (pcbnew.FromMM(0.20), pcbnew.FromMM(0.30))
            and item.GetDrillValue() == pcbnew.FromMM(0.10)):
        board.Remove(item)

# Only critical high-frequency/power returns and pads that cannot reliably
# reach the outer pour get a filled/capped microvia.  Blanket via-in-pad on
# every ground pad is unnecessary, expensive, and visually creates excessive
# holes.
critical = {
    "U1": {"1", "15", "38", "39"},       # ESP32 RF/digital ground
    "U2": {"11", "18", "20"},            # IMU ground/exposed pad
    "U3": {"6", "9"},                    # buck and PowerPAD return
    "U4": {"2"},                          # 3V3 LDO return
    "U5": {"2"},                          # USB ESD return
    "U6": {"2", "25"},                   # USB-UART + exposed pad
    "U7": {"2", "5"},                    # mux control/ground return
    "J9": {"A1", "A12", "B1", "B12"},  # USB-C ground pins
    "C1": {"2"}, "C4": {"2"}, "C7": {"2"}, "C13": {"2"},
    "D1": {"2"}, "J5": {"1"}, "SW1": {"1"},
}

seen = set()
for fp in board.GetFootprints():
    wanted = critical.get(fp.GetReference(), set())
    for pad in fp.Pads():
        if (pad.GetNumber() not in wanted or pad.GetNetname() != "GND"
                or pad.GetAttribute() == pcbnew.PAD_ATTRIB_PTH):
            continue
        # Only front-side pads can reach L2 with a single microvia.
        if not pad.IsOnLayer(pcbnew.F_Cu):
            continue
        q = pad.GetPosition()
        key = (q.x, q.y)
        if key in seen:
            continue
        seen.add(key)
        via = pcbnew.PCB_VIA(board)
        via.SetPosition(q)
        via.SetWidth(pcbnew.FromMM(0.30))
        via.SetDrill(pcbnew.FromMM(0.10))
        via.SetViaType(pcbnew.VIATYPE_MICROVIA)
        via.SetLayerPair(pcbnew.F_Cu, pcbnew.In1_Cu)
        via.SetNet(gnd)
        board.Add(via)

pcbnew.SaveBoard(PATH, board)
print(f"added {len(seen)} GND microvias")
