#pragma once

// Regenerated by the release/build workflow before compiling the firmware.
#define FW_NAME "RC_FlightController"
#define FW_VERSION "V5.4.0-19-g6787b2f"
#define FW_SOURCE_BRANCH "master"
#define FW_SOURCE_COMMIT "6787b2f92d2a"
#define FW_SOURCE_DIRTY 0
#define FW_BUILD_ID "20260709T030553Z-master-6787b2f92d2a"
#define FW_BUILD_TIME_ISO "2026-07-09T03:05:53Z"
