#pragma once

// Regenerated by the release/build workflow before compiling the firmware.
#define FW_NAME "RC_FlightController"
#define FW_VERSION "V5.4.0-14-g14ecc4a"
#define FW_SOURCE_BRANCH "master"
#define FW_SOURCE_COMMIT "14ecc4a25a83"
#define FW_SOURCE_DIRTY 0
#define FW_BUILD_ID "20260701T022956Z-master-14ecc4a25a83"
#define FW_BUILD_TIME_ISO "2026-07-01T02:29:56Z"
